#: include kv/signupscreen.kv
#: include kv/loginscreen.kv
#: include kv/dashboard.kv
#: include kv/historicscreen.kv

ScreenManager:
	id: screen_manager
	size: 1,1
	
	LoginScreen:
		name: "login_screen"
		id: login_screen
	
	DashboardScreen:
		name: "dashboard_screen"
		id: dashboard_screen
	
	SignupScreen:
		name: "signup_screen"
		id: signup_screen
		
		
	HistoricScreen:
		name: "historic_screen"
		id: historic_screen
		

		
		
	
		